spring:
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀 当然默认也是这个，可以不配置
    cache: false  #是否使用缓存
    mode: LEGACYHTML5 # 去除htm5严格校验
    suffix: .html  #后缀名
  mvc:
    static-path-pattern: /static/** # js ,css 等静态文件路径